import {
  GET_TOP_ANIME_START,
  GET_TOP_ANIME_SUCCESS,
  GET_TOP_ANIME_FAILURE,
  getTopAnime,
  GET_UPCOMING_ANIME_START,
  GET_UPCOMING_ANIME_SUCCESS,
  GET_UPCOMING_ANIME_FAILURE,
  getUpcomingAnime
} from "./HomePage"

export {
  GET_TOP_ANIME_START,
  GET_TOP_ANIME_SUCCESS,
  GET_TOP_ANIME_FAILURE,
  getTopAnime,
  GET_UPCOMING_ANIME_START,
  GET_UPCOMING_ANIME_SUCCESS,
  GET_UPCOMING_ANIME_FAILURE,
  getUpcomingAnime
}
